#### Tasca M3 T01
Exercicis de programació numèrica.



- Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.





In [15]:
import numpy as np


def resum_estadistic_basic(x):
    print("Dades estadistiques bàsiques per:\n",x)
    if (x.ndim>1):
        #El parametre d'entrada te més d'una dimensió: Error!!!
        print("Error: El paràmetre d'entrada només pot ser un array d'una dimensió")
    else:
        #El parametre d'entrada es un array:correcte
        print('Rang =',np.ptp(x))
        print('Mitjana =',np.mean(x))
        print('Mediana =',np.median(x))
        print('Desviacio tipica =',np.std(x))
        print('Variança =',np.var(x))
        print('Percentil 25 =',np.percentile(x,25))
        print('Percentil 50 =',np.percentile(x,50))
        print('Percentil 75 =',np.percentile(x,75))
    
arr=np.array([1,2,3,4,5,6,7,8,9])
arr2=np.array([[1,2],[3,4]])
resum_estadistic_basic(arr)
resum_estadistic_basic(arr2)


Dades estadistiques bàsiques per:
 [1 2 3 4 5 6 7 8 9]
Rang = 8
Mitjana = 5.0
Mediana = 5.0
Desviacio tipica = 2.581988897471611
Variança = 6.666666666666667
Percentil 25 = 3.0
Percentil 50 = 5.0
Percentil 75 = 7.0
Dades estadistiques bàsiques per:
 [[1 2]
 [3 4]]
Error: El paràmetre d'entrada només pot ser un array d'una dimensió


- Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [7]:
import numpy as np

# funció sense paràmetres que retorna un array 10x10 de numeros aleatoris entre 0 i 100
def quadrat_aleatori():
    x = np.random.randint(100, size=(10,10))
    return(x)

#crida a la funcio
qa=quadrat_aleatori()
print(qa)


[[77 54 13 36 49 76 64 46 65 22]
 [55 85 40 98 16 73 17 92  5 57]
 [ 0 66 46  0 65 36 50 46 60 51]
 [39 41 24 49 89 15 75 58 55 82]
 [70 88 78 95 84 62  7 59 16 84]
 [70 69 31 58 39 54  3 31 17 16]
 [41 63 70 32 98 84 40 91 54 78]
 [34 79 86 42 81 43 74  8 43 71]
 [70 67 84 53 23 72 43 33  7 99]
 [67 97 87 97  0 76 96 79 87 23]]


- Exercici 3
Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.





In [58]:
import numpy as np

#funció per sumar files i columnes d'una matriu donada
#El paràmetre d'entrada es una matriu N*M
#Retorna uns llista (ndarray) amb dues subllistes; la suma de les files, i la suma deles columnes
def suma_files_columnes(m):
    sfiles = np.sum(m, axis=1)
    scolumnes = np.sum(m, axis=0)
    return([sfiles,scolumnes])
    
#generem una matriu (nfiles x ncolumnes) i la passem com a paràmetre a la funció definida
nfiles=5
ncolumnes=3
mprova=np.random.randint(10,size=(nfiles,ncolumnes))
print(mprova)
resultat=suma_files_columnes(mprova)
print('La suma de les files és:',resultat[0])
print('La suma de les columnnes és:',resultat[1])


[[7 9 3]
 [4 0 0]
 [6 2 3]
 [9 1 1]
 [4 6 2]]
La suma de les files és: [19  4 11 11 12]
La suma de les columnnes és: [30 18  9]


- Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [89]:
import numpy as np

#funcio per calcula el cefient de correlacio de dues variables
#la entrada són les sues variables en format dos arrays
#la sortida és un float que representa el coeficient de correlació
def coef_corr(x,y):
    print('Variable x:',x)
    print('Variable y:',y)
    mitja_x=np.mean(x)
    mitja_y=np.mean(y)
    print('mitja x:',mitja_x)
    print('mitja_y:',mitja_y)
    prod_xy=x*y
    print('x per y:',prod_xy)
    x2=x*x
    print('x quadrat:',x2)
    y2=y*y
    print('y quadrat:',y2)
    suma_xy=sum(prod_xy)
    print('suma de x*y:',suma_xy)
    mitja_xy=np.mean(prod_xy)
    print('Mitja x*y:',mitja_xy)
    covarianca=mitja_xy-(mitja_x*mitja_y)
    print('Covariança:',covarianca)
    #càlcul de desviacions típiques
    mitja_x2=np.mean(x2)
    dt_x=np.sqrt(mitja_x2-mitja_x*mitja_x)
    print('desviació típica x',dt_x)
    mitja_y2=np.mean(y2)
    dt_y=np.sqrt(mitja_y2-mitja_y*mitja_y)
    print('desviació típica y',dt_y)
    #calcul coeficient de correlacio
    resultat=covarianca/(dt_x*dt_y)
    print('coeficient de correlació',resultat)
    return(resultat)

#joc proves 1
a1=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
a2=np.array([2,4,6,8,10,12,14,16,28,20,22,24,26,28,30,32,34,36,38,40])
#joc de proves 2
b1=np.array([2,3,4,4,5,6,6,7,7,8,10,10])
b2=np.array([1,3,2,4,4,4,6,4,6,7,9,10])
#joc de proves 3
c1=np.random.randint(100,size=20)
print(c1)
c2=np.random.randint(100,size=20)
#crida a la funcio i presentacio de resultat
cc=coef_corr(b1,b2)
print('El coeficient de correlacio es:',cc)
if (cc>=0):
    print('Correlació directa')
else:
    print('Correlació inversa')
    
if (abs(cc)>0.8):
    print('Correlació forta')
elif (abs(cc)<0.2):
    print('Correlació feble')
else:
      print('No esta clar')


[ 5 91 64 57 74 79 22 33  8 81 38 81 32 77 49 81 43 47 53 74]
Variable x: [ 2  3  4  4  5  6  6  7  7  8 10 10]
Variable y: [ 1  3  2  4  4  4  6  4  6  7  9 10]
mitja x: 6.0
mitja_y: 5.0
x per y: [  2   9   8  16  20  24  36  28  42  56  90 100]
x quadrat: [  4   9  16  16  25  36  36  49  49  64 100 100]
y quadrat: [  1   9   4  16  16  16  36  16  36  49  81 100]
suma de x*y: 431
Mitja x*y: 35.916666666666664
Covariança: 5.916666666666664
desviació típica x 2.449489742783178
desviació típica y 2.5819888974716116
coeficient de correlació 0.9355071411331451
El coeficient de correlacio es: 0.9355071411331451
Correlació directa
Correlació forta
